### ISSUE TITLE
US1 Render a list of Nurses

### ISSUE THREAD

**Issue by MiketheBite** [MiketheBite/Capstone-project#1]
## Value Proposition

**As a user**  
**I want to view a list of nurses in "My Team" and search for a nurse by their name, so that I can quickly find specific team members**   
​

## Description

![image](https://github.com/MiketheBite/Capstone-project/assets/94850109/56349b50-1962-4a07-8126-3be6b814d0b8)
​

## Acceptance Criteria

- [ ] The "My Team" page should display a list of nurses with their basic information.
- [ ] The list scrolls vertically.
- [ ] The search input should filter the displayed nurses as the user types their name.
- [ ] If the list is empty, a message "You have no team 😩" is shown.
      ​

## Tasks

- [ ] Create a feature branch.
- [ ] Create the "My Team" page component.
- [ ] Create a database, from MongoDB, with the data of each nurse. And connect the database with the component. 
      ​

## Complexity

XL 🤯

**Comment by Charlotte-Ketteler** [comment]
LGTM. :) You'll rock it!
