### ISSUE TITLE
US 5 - Nurse's Work Preference Management Part.2 - Days Off

### ISSUE THREAD

**Issue by MiketheBite** [MiketheBite/Capstone-project#10]
## Value Proposition

As a Nurse Team leader, I want to manage days off for the team so that I can communicate the days off schedule requirements to the general team work schedule. 
​

## Description

​

## Acceptance Criteria

- [ ] Within the "Work Schedule" section, there is an option to insert days off.
- [ ] The user can add, edit and delete them.
- [ ] When adding days off, the user can select dates using a date picker.
- [ ] The features validates the input to ensure all required information is provided.
      ​

## Tasks

- [ ] Create a new branch.
- [ ] Implement options for adding, editing and deleting days off.
- [ ] Integrate a date picker component.
- [ ] Add some styling.
      ​

## Complexity

M

**Comment by HannesOster** [comment]
Hey Miguel, this looks good too, but i would expect at least a sentence for the description. 
Please add a wireframe or a small description, then i will approve you US

**Comment by MiketheBite** [comment]
Done! Thanks

**Comment by Faibs7** [comment]
Hey Miguel, when I click on "Days off", select one or more days and click on "Request your Schedule", I always get the following message: "Please select valid dates before sending." 
Am I testing or misunderstanding the whole thing? Because as soon as I add vacation and select something there, then I also get the days for "Days off" at the bottom and can also delete them.
Could you please explain me the correct procedure for selecting?

**Comment by MiketheBite** [comment]
Yes, you're right. I will have to disassociate the two datepicker's so that they can be submitted separately (even when one is not filled in, as in the case you tested) to be able to submit the selected date and the other (empty) one not being sent.
I still have to implement another Datepicker (for availability by three types of shift) on this page, so I could fix this problem when I already have the code for that third parameter. But it's your decision to give green light to QA now or later, and I thank you for all your feedback and help.

**Comment by Faibs7** [comment]
okay, sounds great. Then I would also fix the problem that the datepickers work independently of each other only once the last datepicker has been added. Cool project including implementation. Keep it up. I would say, then the essential works for now.

**Comment by MiketheBite** [comment]
Thanks for the feedback and the green check. But in the meantime I've started trying to solve the problem you've identified and maybe I'll go back with the PR for this US.

**Comment by donacrisante** [comment]
Hi Miguel, I had a look at your work schedule. It looks great! But there is a bug when you add more than one day. When I add a second day, the days appear several times. Even if I do a reset, the old days appear again and also several times. This needs to be fixed.
