### ISSUE TITLE
US 6 - Nurse's Work Preference Management Part.3 - Availability

### ISSUE THREAD

**Issue by migueljcpinto** [MiketheBite/Capstone-project#11]
## Value Proposition

As a Nurse Team leader, I want to manage the shift availability for the team so that I can integrate all information about work preferences in one work schedule.

## Description

![image](https://github.com/MiketheBite/Capstone-project/assets/94850109/54a4ea4a-be18-4804-89e8-0b60d6e09b11)

​

## Acceptance Criteria

- [ ] Within the "Work Schedule" section, there is an option to insert shift availability.
- [ ] The user can add and delete availability preferences.
- [ ] When adding availability, the user can select dates using a date picker.
- [ ] The feature validates the input to ensure all required information is provided and in the correct format.
      ​

## Tasks

- [ ] Create a new branch.
- [ ] Implement options for adding and deleting availability.
- [ ] Integrate a date picker component.
- [ ] Implement input validation.
     ​

## Complexity

M

**Comment by HannesOster** [comment]
Hey Miguel,

See my last comment to your other US.
Without the missing description youre really doing well!

**Comment by MiketheBite** [comment]
Done!

**Comment by HannesOster** [comment]
Nice, now i gave you the green checkmark  :ok_hand:
