### ISSUE TITLE
US7 - Nurse Team Leader Dashboard - Control Page

### ISSUE THREAD

**Issue by MiketheBite** [MiketheBite/Capstone-project#16]
## Value Proposition

As a Nurse Team Leader, I want to have a dashboard overview of all nurses in Team and their basic informations and schedules
so that I can manage and oversee the entire team's availability and workload efficiently.
​
## Description

A dashboard that displays a list of all users, their roles, and their schedules. It should allow for filtering by role, date, and availability.​

## Acceptance Criteria

- [ ] The dashboard should be accessible only to logged-in admins.
- [ ] Display a list of all users with their respective roles.
- [ ] Each user entry should show a brief overview of their schedule.
- [ ] Provide filtering options to view schedules based on roles, dates, and availability.
- [ ] Clicking on a user should provide a detailed view of their schedule.
      ​

## Tasks

- [ ] Create a Dashboard component.
- [ ] Fetch user data from MongoDB.
- [ ] Implement filtering options.
- [ ] Design and style the dashboard for a user-friendly experience.

## Complexity

M

**Comment by JanaS87** [comment]
Looks good to me 👍 
I'm really looking forward to the app.
