### ISSUE TITLE
US8 - NavBar 

### ISSUE THREAD

**Issue by MiketheBite** [MiketheBite/Capstone-project#19]
## Value Proposition

**As a** ... (User, Author, logged in User...)  
**I want to** ... (describe the goal)  
**so that** ... (describe the reason)  
​

## Description

As the Nurse Team Leader, I want to be able to navigate the app throw a Navbar (or burger menu, don´t know yet) from the dashboard page, for example, to consult a page that shows me the whole team.

## Acceptance Criteria

- [ ] The navbar should be visible and possible to click the navigation links.
- [ ] Each link in the navbar/burger menu should lead to its respective section or page.
- [ ] The navbar/burger menu should be accessible and user-friendly, with clear labels for each link.​

## Tasks

- [ ] Create a new branch.
- [ ] Create a Dashboard component.
- [ ] Design the layout and visuals for the navbar/burger menu.
- [ ] Ensure that the navigation links are correctly routed to their respective sections or pages.​

## Complexity

M (T-Shirt Sizes XS to XL)
