### ISSUE TITLE
US2 - My Team Page - Add, Edit and Delete Buttons

### ISSUE THREAD

**Issue by MiketheBite** [MiketheBite/Capstone-project#2]
## Value Proposition

As a user
I want buttons to add, edit and remove nurses,  
so that I can easily expand, update or remove the team when needed.
​

## Description

![image](https://github.com/MiketheBite/Capstone-project/assets/94850109/dcaf38e0-7f26-48ba-832f-80578096d48d)
​

## Acceptance Criteria

- [ ] The "My Team" page should have a button "⨁". 
- [ ] Clicking the button should navigate to the separate page for adding a new nurse.
- [ ] A "Add Nurse" form is displayed. The form will have some mandatorys input fields and dropdown menus.
- [ ] After clicking "New Nurse" the updated list is displayed. 
- [ ] Each nurse entry on the "My Team" page should have an "Edit" button and a "Delete" button.
- [ ] Clicking the "Edit" button should navigate to the separate page form for editing the nurse's information.
- [ ] Clicking the "Delete" button should remove the nurse from "My Team" after confirmation.
      ​

## Tasks

- [ ] Add the "⨁" button to the "My Team" page.
- [ ] Implement navigation to the separate "Add Nurse" form page when the button is clicked.
- [ ] Add "Edit" and "Delete" buttons to each nurse entry on the "My Team" page.
- [ ] Implement navigation to the separate "Edit Nurse" page when the "Edit" button is clicked.
- [ ] Implement the logic to delete a nurse from "My Team" when the "Delete" button is clicked.

      ​

## Complexity

XL 🤯
