### ISSUE TITLE
US 10 - Upgrading the styles and Tests

### ISSUE THREAD

**Issue by MiketheBite** [MiketheBite/Capstone-project#22]
## Value Proposition

As a Web developer student, working on the current project,
I want to implement consistent styles, conduct comprehensive tests (at least 3), and improve the clarity of the existing codebase, so that the application is more maintainable, user-friendly, and free of critical bugs.
​

## Description

Since it's only to improve the general code and test implementation, there's no need for a descriptive image.
​

## Acceptance Criteria

- [ ] The project remains fully functional after style changes.
- [ ] At least 3 comprehensive tests.
- [ ] All tests pass without any failures.
- [ ] The codebase should have clear comments and documentation where necessary.
- [ ] Code refactoring should result in improved readability without introducing new bugs.
      ​

## Tasks

- [ ] Review the existing codebase to identify areas in need of clarity improvements.
- [ ] Develop a consistent style guide and update the existing one.
- [ ] Refactor code components for better readability and maintainability.
- [ ] Write unit tests for identified modules and components.
- [ ] Review application UI/UX to ensure that styling changes don’t negatively affect user experience.

      ​

## Complexity

M
