### ISSUE TITLE
US3 - My Team Page - Edit and Delete a Nurse

### ISSUE THREAD

**Issue by MiketheBite** [MiketheBite/Capstone-project#3]
## Value Proposition

As a user,
I want buttons to edit and delete nurses from "My Team",
so that I can update their information or remove them from the team list.

## Description

![image](https://github.com/MiketheBite/Capstone-project/assets/94850109/eb9750d3-d149-48bd-af0a-30977bf95015)​

## Acceptance Criteria

- [ ] Each nurse entry on the "My Team" page should have an "Edit" (✏️) button and a "Delete" (🗑️) button.
- [ ] Clicking the "Edit" button should navigate to a separate page form for editing the nurse's information.
- [ ] This page form should be similar to the "New Nurse" page form, but the submit button should just update the nurse information.
- [ ] Clicking the "Delete" button should remove the nurse from "My Team" after confirmation.
      ​
## Tasks

- [ ] Create a new feature branch.
- [ ] Add "Edit" and "Delete" buttons to each nurse entry on the "My Team" page.
- [ ] Implement navigation to the separate "Edit Nurse" page when the "Edit" button is clicked.
- [ ] Create a form component for the edit function page.
- [ ] Implement the logic to delete a nurse from "My Team" when the "Delete" button is clicked.
      ​

## Complexity

XL 😵‍💫

**Comment by Kheirah** [comment]
Your story makes a lot of sense! BUT 😁 

It's huge. You could dissect it into _at least_ two smaller stories. For example, features that could be their own user story:
- the search function
- the detail page + form component (without update & delete buttons)
- update and delete functionality of your two buttons

I would recomment you think about it and if you deem it appropriate, create smaller user stories. If you think you want to take on this single huge story, you have a green light as well.

**Comment by MiketheBite** [comment]
I already had a drop of sweat running down my forehead just waiting for your review! 😅 You're right, but maybe I'll try to work on this US this time and for the next ones I'll be more careful in my planning. Thanks a lot!
