### ISSUE TITLE
US3 - My Team Page - Search function and Nurse details

### ISSUE THREAD

**Issue by MiketheBite** [MiketheBite/Capstone-project#4]
## Value Proposition

As a Nurse Team leader, 
I want to search for a nurse by their name, so that I can quickly find specific team members, and I want to be able to access more detailed information about each nurse by clicking on their name.
​

## Description

![image](https://github.com/MiketheBite/Capstone-project/assets/94850109/fc0bb44f-f4fb-40b9-b824-4ec12ca5b0c0)​

## Acceptance Criteria

- [ ] The search input should filter the displayed nurses as the user types their name.
- [ ] Open a page for each nurse profile.
- [ ] On the profile page, have a button that directs to the edit page of the same profile.

## Tasks

- [ ] Implement the search functionality to filter nurses by name.
- [ ] Implement the functionality to open a profile page for each nurse.

      ​

## Complexity

L

**Comment by Kheirah** [comment]
Another gigantic story 😀 
Let's cut it into **three smaller user stories:**
- holidays
- days off
- availability

For each of these make a user story **that implements adding, updating, and deleting.**
**Connect these operation to the backend** such that the info is reflected in the database.

Take small bites🍔

**Comment by HannesOster** [comment]
Hey Miguel,

This looks goot to me! Very well structured and easy to follow you. :)

**Comment by NicoleHoerner** [comment]
Even though you removed the editing function, it seems to be quite a large user story. But everything makes sense. Nice app so far😃
Bom trabalho!💪
